name: hub-adapter-sample
base: core20
version: '0.1'
summary: Adapter
description: |
  Adapter

grade: stable
confinement: strict

parts:
  launcher:
    plugin: dump
    source: .
    prime:
      - bin/main.py
    stage:
      - bin/main.py
    organize:
      main.py: bin/main.py
  adapter:
    plugin: python
    python-packages:
      - autobahn[twisted,serialization]

apps:
  hub-adapter-sample:
    command: bin/python3 -u $SNAP/bin/main.py

plugs:
  sockdir:
    interface: content
    content: sockdir
    target: $SNAP_COMMON
    default-provider: thinghub:sockdir
